items/urls.py
from django.urls import path
from items import views


app_name = "items_app"


urlpatterns = [
    path('items/index/', views.index, name="index"),
    # path("items-create-view/", views.ItemCreateView.as_view(), name="items-create-view"),
    path("items-create-view/", views.ItemCreateView.as_view(), name="items-create-view"),
    path("items-detail-view/<pk>/", views.ItemDetailView.as_view(), name="items-detail-view"),
    path("items-update-view/<pk>/", views.ItemUpdateView.as_view(), name="items-update-view"),
    path("items-delete-view/<pk>/", views.ItemDeleteView.as_view(), name="items-delete-view"),
    path("items-list-view/", views.ItemListView.as_view(), name="items-list-view"),
    path('items/index/', views.index, name="items-index"),
    path('items/', views.items, name="items"),
    path('items-above-minimum-stock', views.above_minimum_stock, name="items-above-minimum-stock"),
    path('search/', views.SearchResultsView.as_view(), name="search-result"),
    path('search-form/', views.search, name="search-form"),
    path("company-delete-view/<pk>/", views.CompanyDeleteView.as_view(), name="company-delete-view"),
    path("company-detail-view/<pk>/", views.CompanyDetailView.as_view(), name="company-detail-view"),
    path("companies/", views.CompanyListView.as_view(), name="companies"),
    path("companies_template/", views.CompanyTemplateView.as_view(), name="companies-template-view"),
    path("company-model-form-view/", views.CompanyModelFormView.as_view(), name="company-model-form-view"),
    path("company-template-view/", views.CompanyTemplateView.as_view(), name="company-template-view"),
    path("company-update-view/<pk>/", views.CompanyUpdateView.as_view(), name="company-update-view"),
    path('units-create-view/', views.UnitCreateView.as_view(), name="units-create-view"),
    path('units-detail-view/<pk>/', views.UnitDetailView.as_view(), name="units-detail-view"),
    path('units-update-view/<pk>/', views.UnitUpdateView.as_view(), name="units-update-view"),
    path('units-delete-view/<pk>/', views.UnitDeleteView.as_view(),
         name="units-delete-view"),
    path('units-list-view/', views.UnitListView.as_view(), name="units-list-view"),
    path('units/index/', views.index, name="units-index"),
    path('units/', views.units, name="units"),
    path('category-create-view/', views.CategoryCreateView.as_view(), name="category-create-view"),
    path('category-detail-view/<pk>/', views.CategoryDetailView.as_view(), name="category-detail-view"),
    path('category-update-view/<pk>/', views.CategoryUpdateView.as_view(), name="category-update-view"),
    path('category-delete-view/<pk>/', views.CategoryDeleteView.as_view(),
         name="category-delete-view"),
    path('category-list-view/', views.CategoryListView.as_view(), name="category-list-view"),
    path('category/index/', views.index, name="index"),
    path('category/', views.category, name="category"),
]

locations/urls.py
from django.urls import path
from locations import views


app_name = "locations_app"


urlpatterns = [
    path('location/index/', views.index, name="location-index"),
    path('location-detail-view/<pk>/', views.LocationDetailView.as_view(), name="location-detail-view"),
    path('location-create-view/', views.LocationCreateView.as_view(), name="location-create-view"),
    path('location-update-view/<pk>/', views.LocationUpdateView.as_view(), name="location-update-view"),
    path('location-delete-view/<pk>/', views.LocationDeleteView.as_view(),
         name="location-delete-view"),
    path('location-list-view/', views.LocationListView.as_view(), name="location-list-view"),
    path('location/', views.location, name="location"),
    path('location-with-stock', views.location_with_stock, name="location-with-stock"),

]

warehouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="homepage"),
    path('admin/', admin.site.urls),
    path('items/', include('items.urls')),
    path('locations/', include('locations.urls')),
    path('orders/', include('orders.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locations/models.py
from django.db import models


class Location(models.Model):
    location = models.CharField(max_length=64)
    description = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return f" {self.location}"


class LocationDetail(models.Model):
    warehouse = models.ForeignKey(Location, on_delete=models.CASCADE, related_name="warehouse")
    loc_section = models.IntegerField(blank=True, null=True)
    loc_shelf = models.CharField(max_length=4, blank=True, null=True)
    is_occupied = models.BooleanField(default=False)

    def __str__(self):
        return f" {self.warehouse}"

locations/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import ListView, DeleteView, UpdateView, DetailView, CreateView

from items.models import Item
from locations.models import Location


def location(request):
    return render(
        request,
        template_name="location/location.html",
        context={"location": Location.objects.all().order_by('location')}
    )


def index(request):
    return render(
        request,
        template_name="location/index.html"
    )


class LocationDetailView(DetailView):
    model = Location
    template_name = "location/my_location.html"


class LocationCreateView(LoginRequiredMixin, CreateView):
    model = Location
    template_name = "form.html"
    fields = "__all__"
    success_url = reverse_lazy("locations_app:location-list-view")


class LocationDeleteView(LoginRequiredMixin, DeleteView):
    model = Location
    template_name = "location/delete_location.html"
    success_url = reverse_lazy("locations_app:location-list-view")


class LocationListView(ListView):
    model = Location
    template_name = "location/list_view_location.html"


class LocationUpdateView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = ("location", "description")
    template_name = "form.html"
    success_url = reverse_lazy("locations_app:location-list-view")


def location_with_stock(request):
    locations_list = Item.objects.order_by('location').exclude(location=None)
    page = request.GET.get('page', 1)

    paginator = Paginator(locations_list, 10)
    try:
        locations_list = paginator.page(page)
    except PageNotAnInteger:
        locations_list = paginator.page(1)
    except EmptyPage:
        locations_list = paginator.page(paginator.num_pages)
    return render(
        request,
        template_name='location/location_with_stock.html',
        context={'items': locations_list},
    )

templates/location/delete_location.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Do you really want to delete LOCATION with name: {{ object.location }}</p>
    <input type="submit" value="Delete">
</form>
{% endblock %}

templates/location/index.html
{% extends "base.html" %}
{% block content %}
    <p><a href="{% url 'locations_app:location' %}">LOCATION LIST</a></p>
    <p><a href="{% url 'locations_app:location-with-stock' %}">LOCATION WITH STOCK</a></p>
{% endblock %}

templates/location/list_view_location.html
{% extends "base.html" %}
{% block content %}
    {% for o in object_list %}
        <li> {{ o }} </li>
    {% endfor %}
    <a href="{% url 'locations_app:location' %}">RETURN TO INDEX LOCATION PAGE</a>
{% endblock %}

templates/location/location.html
{% extends "base.html" %}
{% block content %}
<h1>LOCATION LIST:</h1>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="5%">ID</th>
            <th scope="col" width="25%">Location</th>
            <th scope="col" width="40%">Description</th>
        </tr>
        </thead>
        <tbody>
        {% for i in location %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'locations_app:location-detail-view' pk=i.pk %}">{{ i.location }}</a></td>
                <td> {{ i.description }} </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if request.user.is_staff %}
        <p><a href="{% url 'locations_app:location-create-view' %}">ADD location</a></p>
    {% endif %}
    <a href="{% url 'locations_app:location-index' %}">RETURN TO DASHBOARD Location</a>
{% endblock %}

templates/location/location_with_stock.html
{% extends "base.html" %}
{% block content %}
<h2>LOCATION WITH STOCK:</h2>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="15%">Name</th>
            <th scope="col" width="53%">Description Item</th>
            <th scope="col" width="4%">Quantity</th>
            <th scope="col" width="3%" style="text-align: center; vertical-align: middle;">Location</th>
        </tr>
        </thead>
        <tbody>
        {% for i in items %}
            <tr>
                <th scope="row" style="vertical-align: middle;">{{ forloop.counter }}</th>
                <td>{{ i.description }} </td>
                <td>{{ i.quantity }} </td>
                <td style="vertical-align: middle;">{{ i.location }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<br>

{% if items.has_other_pages %}
  <ul class="pagination">
    {% if items.has_previous %}
      <li><a href="?page={{ items.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in items.paginator.page_range %}
      {% if items.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if items.has_next %}
      <li><a href="?page={{ items.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
    <a href="{% url 'items_app:items-index' %}">RETURN TO DASHBOARD</a>
{% endblock %}

templates/location/my_location.html
{% extends "base.html" %}
{% block content %}
    <p>Location ID: {{ location.id }}</p>
    <p>LOCATION NAME: {{ location.location }}</p>
    {% if request.user.is_staff %}
        <p><a href="{% url 'locations_app:location-update-view' pk=location.pk %}">UPDATE Location</a></p>
        <p><a href="{% url 'locations_app:location-delete-view' pk=location.pk %}">DELETE Location</a></p>
    {% endif %}
    <a href="{% url 'locations_app:location' %}">RETURN TO LOCATION LIST</a>
{% endblock %}