items/urls.py
from django.urls import path
from items import views


app_name = "items_app"


urlpatterns = [
    path('items/index/', views.index, name="index"),
    # path("items-create-view/", views.ItemCreateView.as_view(), name="items-create-view"),
    path("items-create-view/", views.ItemCreateView.as_view(), name="items-create-view"),
    path("items-detail-view/<pk>/", views.ItemDetailView.as_view(), name="items-detail-view"),
    path("items-update-view/<pk>/", views.ItemUpdateView.as_view(), name="items-update-view"),
    path("items-delete-view/<pk>/", views.ItemDeleteView.as_view(), name="items-delete-view"),
    path("items-list-view/", views.ItemListView.as_view(), name="items-list-view"),
    path('items/index/', views.index, name="items-index"),
    path('items/', views.items, name="items"),
    path('items-above-minimum-stock', views.above_minimum_stock, name="items-above-minimum-stock"),
    path('search/', views.SearchResultsView.as_view(), name="search-result"),
    path('search-form/', views.search, name="search-form"),
    path("company-delete-view/<pk>/", views.CompanyDeleteView.as_view(), name="company-delete-view"),
    path("company-detail-view/<pk>/", views.CompanyDetailView.as_view(), name="company-detail-view"),
    path("companies/", views.CompanyListView.as_view(), name="companies"),
    path("companies_template/", views.CompanyTemplateView.as_view(), name="companies-template-view"),
    path("company-model-form-view/", views.CompanyModelFormView.as_view(), name="company-model-form-view"),
    path("company-template-view/", views.CompanyTemplateView.as_view(), name="company-template-view"),
    path("company-update-view/<pk>/", views.CompanyUpdateView.as_view(), name="company-update-view"),
    path('units-create-view/', views.UnitCreateView.as_view(), name="units-create-view"),
    path('units-detail-view/<pk>/', views.UnitDetailView.as_view(), name="units-detail-view"),
    path('units-update-view/<pk>/', views.UnitUpdateView.as_view(), name="units-update-view"),
    path('units-delete-view/<pk>/', views.UnitDeleteView.as_view(),
         name="units-delete-view"),
    path('units-list-view/', views.UnitListView.as_view(), name="units-list-view"),
    path('units/index/', views.index, name="units-index"),
    path('units/', views.units, name="units"),
    path('category-create-view/', views.CategoryCreateView.as_view(), name="category-create-view"),
    path('category-detail-view/<pk>/', views.CategoryDetailView.as_view(), name="category-detail-view"),
    path('category-update-view/<pk>/', views.CategoryUpdateView.as_view(), name="category-update-view"),
    path('category-delete-view/<pk>/', views.CategoryDeleteView.as_view(),
         name="category-delete-view"),
    path('category-list-view/', views.CategoryListView.as_view(), name="category-list-view"),
    path('category/index/', views.index, name="index"),
    path('category/', views.category, name="category"),
]

warehouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="homepage"),
    path('admin/', admin.site.urls),
    path('items/', include('items.urls')),
    path('locations/', include('locations.urls')),
    path('orders/', include('orders.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/units/delete_units.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Do you really want to delete units with name: {{ object.unit }}</p>
    <input type="submit" value="Delete">
</form>
{% endblock %}

templates/units/index.html
{% extends "base.html" %}
{% block content %}
    <p><a href="{% url 'items_app:units' %}">UNIT</a></p>
{% endblock %}

templates/units/list_view_units.html
{% extends "base.html" %}
{% block content %}
    {% for o in object_list %}
        <li> {{ o }} </li>
    {% endfor %}
    <a href="{% url 'items_app:units' %}">RETURN TO INDEX PAGE</a>
{% endblock %}

templates/units/my_units.html
{% extends "base.html" %}
{% block content %}
    <p>UNITS ID: {{ unit.id }}</p>
    <p>UNITS NAME: {{ unit.name }}</p>
    {% if request.user.is_staff %}
        <p><a href="{% url 'items_app:units-update-view' pk=unit.pk %}">UPDATE UNIT</a></p>
        <p><a href="{% url 'items_app:units-delete-view' pk=unit.pk %}">DELETE UNIT</a></p>
    {% endif %}
    <a href="{% url 'items_app:units' %}">RETURN TO UNITS LIST</a>
{% endblock %}

templates/units/units.html
{% extends "base.html" %}
{% block content %}
<h1>UNITS LIST:</h1>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="5%">ID</th>
            <th scope="col" width="15%">Unit</th>
            <th scope="col" width="40%">Description</th>
        </tr>
        </thead>
        <tbody>
        {% for i in units %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'items_app:units-detail-view' pk=i.pk %}">{{ i.name }}</a></td>
                <td>{{ i.description }} </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if request.user.is_staff %}
        <p><a href="{% url 'items_app:units-create-view' %}">ADD UNIT</a></p>
    {% endif %}
    <a href="{% url 'items_app:index' %}">RETURN TO DASHBOARD</a>
{% endblock %}