items/urls.py
from django.urls import path
from items import views


app_name = "items_app"


urlpatterns = [
    path('items/index/', views.index, name="index"),
    # path("items-create-view/", views.ItemCreateView.as_view(), name="items-create-view"),
    path("items-create-view/", views.ItemCreateView.as_view(), name="items-create-view"),
    path("items-detail-view/<pk>/", views.ItemDetailView.as_view(), name="items-detail-view"),
    path("items-update-view/<pk>/", views.ItemUpdateView.as_view(), name="items-update-view"),
    path("items-delete-view/<pk>/", views.ItemDeleteView.as_view(), name="items-delete-view"),
    path("items-list-view/", views.ItemListView.as_view(), name="items-list-view"),
    path('items/index/', views.index, name="items-index"),
    path('items/', views.items, name="items"),
    path('items-above-minimum-stock', views.above_minimum_stock, name="items-above-minimum-stock"),
    path('search/', views.SearchResultsView.as_view(), name="search-result"),
    path('search-form/', views.search, name="search-form"),
    path("company-delete-view/<pk>/", views.CompanyDeleteView.as_view(), name="company-delete-view"),
    path("company-detail-view/<pk>/", views.CompanyDetailView.as_view(), name="company-detail-view"),
    path("companies/", views.CompanyListView.as_view(), name="companies"),
    path("companies_template/", views.CompanyTemplateView.as_view(), name="companies-template-view"),
    path("company-model-form-view/", views.CompanyModelFormView.as_view(), name="company-model-form-view"),
    path("company-template-view/", views.CompanyTemplateView.as_view(), name="company-template-view"),
    path("company-update-view/<pk>/", views.CompanyUpdateView.as_view(), name="company-update-view"),
    path('units-create-view/', views.UnitCreateView.as_view(), name="units-create-view"),
    path('units-detail-view/<pk>/', views.UnitDetailView.as_view(), name="units-detail-view"),
    path('units-update-view/<pk>/', views.UnitUpdateView.as_view(), name="units-update-view"),
    path('units-delete-view/<pk>/', views.UnitDeleteView.as_view(),
         name="units-delete-view"),
    path('units-list-view/', views.UnitListView.as_view(), name="units-list-view"),
    path('units/index/', views.index, name="units-index"),
    path('units/', views.units, name="units"),
    path('category-create-view/', views.CategoryCreateView.as_view(), name="category-create-view"),
    path('category-detail-view/<pk>/', views.CategoryDetailView.as_view(), name="category-detail-view"),
    path('category-update-view/<pk>/', views.CategoryUpdateView.as_view(), name="category-update-view"),
    path('category-delete-view/<pk>/', views.CategoryDeleteView.as_view(),
         name="category-delete-view"),
    path('category-list-view/', views.CategoryListView.as_view(), name="category-list-view"),
    path('category/index/', views.index, name="index"),
    path('category/', views.category, name="category"),
]

orders/urls.py
from django.urls import path

from . import views

app_name = "orders_app"


urlpatterns = [
    path("orders/index/", views.index, name="orders-index"),
    path("orders-update-view/<pk>/", views.OrderUpdateView.as_view(), name="orders-update-view"),
    path("orders-delete-view/<pk>/", views.OrderDeleteView.as_view(), name="orders-delete-view"),
    path("orders-detail-view/<pk>/", views.OrderDetailView.as_view(), name="orders-detail-view"),
    path("active-orders-detail-view/<pk>/", views.ActiveOrderDetailView.as_view(), name="active-orders-detail-view"),
    path("orders-list-view/", views.OrderListView.as_view(), name="orders-list-view"),
    path("orders/", views.orders, name="orders"),
    path("order-details", views.order_details, name="order-details"),
    path("add-to-cart/<pk>/", views.add_to_cart, name="add-to-cart"),
    path("order-summary", views.OrderSummary.as_view(), name="order-summary"),
    path("remove-single-item-from-cart/<pk>/", views.remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path("complete-order", views.complete_order, name="complete-order"),
    path("active-orders", views.active_orders, name="active-orders"),
    path("completed-orders", views.completed_orders, name="completed-orders"),
    path("items-below-minimum-stock", views.below_minimum_stock, name="items-below-minimum-stock"),
    path("frequently-ordered", views.frequently_ordered, name="frequently-ordered"),
    ]

warehouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="homepage"),
    path('admin/', admin.site.urls),
    path('items/', include('items.urls')),
    path('locations/', include('locations.urls')),
    path('orders/', include('orders.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.conf import settings
from django.db import models

from items.models import Item


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, blank=True, null=True)
    order_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    items = models.ManyToManyField("OrderDetail")

    def __str__(self):
        return f"{self.user.username}"


class OrderDetail(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="item")
    quantity = models.PositiveSmallIntegerField(default=1)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, blank=True, null=True)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.item.producer_no} x {self.quantity}"

orders/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import F
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DeleteView, DetailView, ListView, UpdateView, View

from items.models import Item
from .models import Order, OrderDetail


class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    fields = ("ordered",)
    template_name = "form.html"
    success_url = reverse_lazy("orders_app:active-orders")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.ordered = False
        order_items = self.object.items.all()
        order_items.update(ordered=False)
        for item in order_items:
            item.save()
        return super().post(request, *args, **kwargs)


class OrderDeleteView(LoginRequiredMixin, DeleteView):
    model = Order
    template_name = "items/delete.html"
    success_url = reverse_lazy("orders_app:orders-list-view")


class OrderDetailView(DetailView):
    model = Order
    template_name = "orders/my_order.html"


class ActiveOrderDetailView(DetailView):
    model = Order
    template_name = "orders/my_active_order.html"


class OrderListView(ListView):
    template_name = "orders/orders.html"
    model = Order

    def get_ordering(self):
        ordering = self.request.GET.get("ordering", "-order_date")
        return ordering


@login_required
def orders(request):
    return render(
        request,
        template_name="orders/orders.html",
        context={"object_list": Order.objects.all().order_by("-order_date")},
    )


def order_details(request):
    return render(
        request,
        template_name="orders/order_details.html",
        context={"object_list": OrderDetail.objects.all().order_by("-item")},
    )


def index(request):
    return render(
        request,
        template_name="orders/index.html"
    )


class OrderSummary(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            return render(self.request,
                          template_name='orders/order_summary.html',
                          context={
                              "order_summary": order,
                          },
                          )
        except ObjectDoesNotExist:
            return render(self.request,
                          template_name='orders/order_summary.html',
                          )


@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_item, created = OrderDetail.objects.get_or_create(item=item, user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        print(order_qs)
        if order.items.filter(item__pk=item.pk).exists():
            order_item.quantity += 1
            order_item.save()
            return redirect("orders_app:order-summary")
        else:
            order.items.add(order_item)
            return redirect("orders_app:order-summary")

    else:
        order = Order.objects.create(user=request.user, order_date=timezone.now())
        order.items.add(order_item)
        return redirect("orders_app:order-summary")


@login_required
def remove_single_item_from_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(item__pk=item.pk).exists():
            order_item = OrderDetail.objects.filter(item=item, user=request.user, ordered=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
            else:
                order_item.quantity -= 1
                order.items.remove(order_item)
                order_item.ordered = True
            order_item.save()

            return redirect("orders_app:order-summary")
        else:
            return redirect("items_app:items-detail-view", pk=pk)
    else:
        return redirect("items_app:items-detail-view", pk=pk)


@login_required
def complete_order(request):
    order = Order.objects.get(user=request.user, ordered=False)
    order_items = order.items.all()
    order_items.update(ordered=True)
    for item in order_items:
        item.save()

    order.ordered = True
    order.save()

    return redirect("homepage")


@login_required
def active_orders(request):
    return render(
        request,
        template_name="orders/active_orders.html",
        context={"object_list": Order.objects.filter(ordered=False).order_by("-order_date")},
    )


def completed_orders(request):
    return render(
        request,
        template_name="orders/completed_orders.html",
        context={"object_list": Order.objects.filter(ordered=True).order_by("-order_date")},
    )


def below_minimum_stock(request):
    items_list = Item.objects.order_by('name').exclude(quantity__gte=F('minimum_quantity'))
    page = request.GET.get('page', 1)

    paginator = Paginator(items_list, 10)
    try:
        items_list = paginator.page(page)
    except PageNotAnInteger:
        items_list = paginator.page(1)
    except EmptyPage:
        items_list = paginator.page(paginator.num_pages)
    return render(
        request,
        template_name='orders/items_below_min.html',
        context={'items': items_list},
    )


def frequently_ordered(request):
    from django.db.models import Sum
    object_list = OrderDetail.objects.filter(ordered="True").values(
        "item__producer_no").annotate(total_quantity=Sum("quantity")).order_by("-total_quantity")[:10]
    return render(
        request,
        template_name="orders/frequently_ordered.html",
        context={
            "object_list": object_list,
        },
    )

templates/orders/active_orders.html
{% extends "base.html" %}
{% block content %}
<h1>OPEN ORDERS:</h1>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Order date</th>
            <th scope="col">Ordered by</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        {% for order in object_list %}
            <tr>
                <td><a href="{% url 'orders_app:active-orders-detail-view' pk=order.pk %}">{{ order.id }}</a></td>
                <td>{{ order.order_date|date:"d M, Y" }} </td>
                <td>{{ order.user.username }} </td>
                {% if order.ordered == True %}
                <td> Order placed </td>
                {% else %}
                <td> In preparation </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/orders/completed_orders.html
{% extends "base.html" %}
{% block content %}
<h1>PLACED ORDERS:</h1>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Order date</th>
            <th scope="col">Ordered by</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        {% for order in object_list %}
            <tr>
                <td><a href="{% url 'orders_app:orders-detail-view' pk=order.pk %}">{{ order.id }}</a></td>
                <td>{{ order.order_date|date:"d M, Y" }} </td>
                <td>{{ order.user.username }} </td>
                {% if order.ordered == True %}
                <td> Order placed </td>
                {% else %}
                <td> In preparation </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/orders/frequently_ordered.html
{% extends "base.html" %}

{% block content %}
<h1>ITEMS FREQUENTLY ORDERED:</h1>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Item No</th>
            <th scope="col">Quantity</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <td>{{ item.item__producer_no }}</td>
                <td>{{ item.total_quantity }} </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/orders/index.html
{% extends "base.html" %}
{% block content %}
    <p><a href="{% url 'orders_app:active-orders' %}">OPEN ORDERS</a></p>
    <p><a href="{% url 'orders_app:completed-orders' %}">COMPLETED ORDERS</a></p>
    <p><a href="{% url 'orders_app:items-below-minimum-stock' %}">ITEMS BELOW MINIMUM STOCK</a></p>
    <p><a href="{% url 'orders_app:frequently-ordered' %}">ITEMS FREQUENTLY ORDERED</a></p>
{% endblock %}

templates/orders/items_below_min.html
{% extends "base.html" %}
{% block content %}
<h2>ITEMS BELOW MINIMUM STOCK:</h2>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="5%">No</th>
            <th scope="col" width="15%">Name</th>
            <th scope="col" width="53%">Description</th>
            <th scope="col" width="15%" style="text-align: center; vertical-align: middle;">Producer</th>
            <th scope="col" width="5%" style="text-align: center; vertical-align: middle;">Unit</th>
            <th scope="col" width="7%" style="text-align: center; vertical-align: middle;">Quantity</th>
        </tr>
        </thead>
        <tbody>
        {% for i in items %}
            <tr>
                <th scope="row" style="vertical-align: middle;">{{ forloop.counter }}</th>
                <td style="vertical-align: middle;">
                    <a href="{% url 'items_app:items-detail-view' pk=i.pk %}">{{ i.name }}</a></td>
                <td>{{ i.description }} </td>
                <td style="text-align: center; vertical-align: middle;">{{ i.producer }} </td>
                <td style="text-align: center; vertical-align: middle;">{{ i.unit }} </td>
                <td style="text-align: center; vertical-align: middle;">{{ i.quantity }} </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<br>

{% if items.has_other_pages %}
  <ul class="pagination">
    {% if items.has_previous %}
      <li><a href="?page={{ items.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in items.paginator.page_range %}
      {% if items.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if items.has_next %}
      <li><a href="?page={{ items.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

templates/orders/my_active_order.html
{% extends "base.html" %}
{% block content %}
<h1>ORDERS:</h1>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Order date</th>
            <th scope="col">Items</th>
            <th scope="col">Ordered by</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.order_date|date:"d M, Y" }} </td>
            <td>{% for ele in order.items.all %}
                Item no: {{ forloop.counter }}
                <ul>
                    <li> {{ ele }} </li>
                    <li> Supplier: {% if ele.item.supplier %}{{ ele.item.supplier }}{% endif %}</li>
                    <li> Supplier no: {{ ele.item.supplier_no }} </li>
                </ul>
                {% endfor %}
            </td>
            <td>{{ order.user.username }} </td>
            {% if order.ordered == True %}
                <td> Order placed </td>
                {% else %}
                    <td> In preparation </td>
            {% endif %}
        </tr>
        </tbody>
    </table>
    {% if request.user.is_staff %}
        <p><a href="{% url 'orders_app:orders-delete-view' pk=order.pk %}">DELETE ORDER</a></p>
    {% endif %}
{% endblock %}

templates/orders/my_order.html
{% extends "base.html" %}
{% block content %}
<h1>ORDERS:</h1>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Order date</th>
            <th scope="col">Items</th>
            <th scope="col">Ordered by</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.order_date|date:"d M, Y" }} </td>
            <td>{% for ele in order.items.all %}
                Item no: {{ forloop.counter }}
                <ul>
                    <li> {{ ele }} </li>
                    <li> Supplier: {% if ele.item.supplier %}{{ ele.item.supplier }}{% endif %}</li>
                    <li> Supplier no: {{ ele.item.supplier_no }} </li>
                </ul>
                {% endfor %}
            </td>
            <td>{{ order.user.username }} </td>
            {% if order.ordered == True %}
                <td> Order placed </td>
                {% else %}
                    <td> In preparation </td>
            {% endif %}
        </tr>
        </tbody>
    </table>
    {% if request.user.is_staff %}
        <p><a href="{% url 'orders_app:orders-update-view' pk=order.pk %}">UPDATE ORDER</a></p>
        <p><a href="{% url 'orders_app:orders-delete-view' pk=order.pk %}">DELETE ORDER</a></p>
    {% endif %}
{% endblock %}

templates/orders/order_details.html
{% extends "base.html" %}
{% block content %}
<h1>ORDERS:</h1>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">User</th>
            <th scope="col">Producer no</th>
            <th scope="col">Quantity</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        {% for o in object_list %}
            <tr>
                <td>{{ o.user_id }}</td>
                <td>{{ o.item }} </td>
                <td>{{ o.quantity }} </td>
                <td>{{ o.ordered }} </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/orders/order_summary.html
{% extends 'base.html' %}
{%block content%}
  <main>
    <div class="container">
        <div class="table-responsive text-nowrap">
          <h2>Order Summary</h2>
          <table class="table">
            <thead>
              <tr>
                  <th scope="col">#</th>
                <th scope="col">Item producer_no</th>
                <th scope="col">Description</th>
                <th scope="col">Supplier</th>
                <th scope="col">Supplier no</th>
                <th scope="col">Quantity</th>
              </tr>
            </thead>
            <tbody>
            {% if order_summary.items.count.all == 0 %}
              <tr>
                <td colspan='5'>Your order is empty</td>
              </tr>
            {% endif %}
              <tr>
                {% for order_item in order_summary.items.all %}
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ order_item.item.producer_no }}</td>
                  <td>{{ order_item.item.description }}</td>
                 <td>{% if order_item.item.supplier %}{{ order_item.item.supplier }}{% endif %}</td>
                 <td>{{ order_item.item.supplier_no }}</td>
                <td>
                  {{ order_item.quantity }}
                <a href="{% url 'orders_app:remove-single-item-from-cart' pk=order_item.item.pk %}"> - </a>
                  /
                <a href="{% url 'orders_app:add-to-cart' pk=order_item.item.pk %}"> + </a>
                </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan='5'>Your order is empty</td>
                </tr>
              {% endfor %}
              <tr>
                <td colspan="6">
                  <a class="btn btn-dark float-right " href="{% url 'items_app:search-form' %}">Continue Shopping</a>
                  <br>
                  <br>
                  <br>
                </td>
              </tr>
            <tr>
                <td colspan="6">
                  <a class="btn btn-dark float-right " href="{% url 'orders_app:complete-order' %}">Order</a>
                </td>
            </tr>
            </tbody>
          </table>
        </div>
    </div>
  </main>
{% endblock content %}

templates/orders/orders.html
{% extends "base.html" %}
{% block content %}
<h1>ALL ORDERS:</h1>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Order date</th>
            <th scope="col">Ordered by</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        {% for order in object_list %}
            <tr>
                <td><a href="{% url 'orders_app:orders-detail-view' pk=order.pk %}">{{ order.id }}</a></td>
                <td>{{ order.order_date|date:"d M, Y" }} </td>
                <td>{{ order.user.username }} </td>
                {% if order.ordered == True %}
                <td> Order placed </td>
                {% else %}
                <td> In preparation </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}