items/urls.py
from django.urls import path
from items import views


app_name = "items_app"


urlpatterns = [
    path('items/index/', views.index, name="index"),
    # path("items-create-view/", views.ItemCreateView.as_view(), name="items-create-view"),
    path("items-create-view/", views.ItemCreateView.as_view(), name="items-create-view"),
    path("items-detail-view/<pk>/", views.ItemDetailView.as_view(), name="items-detail-view"),
    path("items-update-view/<pk>/", views.ItemUpdateView.as_view(), name="items-update-view"),
    path("items-delete-view/<pk>/", views.ItemDeleteView.as_view(), name="items-delete-view"),
    path("items-list-view/", views.ItemListView.as_view(), name="items-list-view"),
    path('items/index/', views.index, name="items-index"),
    path('items/', views.items, name="items"),
    path('items-above-minimum-stock', views.above_minimum_stock, name="items-above-minimum-stock"),
    path('search/', views.SearchResultsView.as_view(), name="search-result"),
    path('search-form/', views.search, name="search-form"),
    path("company-delete-view/<pk>/", views.CompanyDeleteView.as_view(), name="company-delete-view"),
    path("company-detail-view/<pk>/", views.CompanyDetailView.as_view(), name="company-detail-view"),
    path("companies/", views.CompanyListView.as_view(), name="companies"),
    path("companies_template/", views.CompanyTemplateView.as_view(), name="companies-template-view"),
    path("company-model-form-view/", views.CompanyModelFormView.as_view(), name="company-model-form-view"),
    path("company-template-view/", views.CompanyTemplateView.as_view(), name="company-template-view"),
    path("company-update-view/<pk>/", views.CompanyUpdateView.as_view(), name="company-update-view"),
    path('units-create-view/', views.UnitCreateView.as_view(), name="units-create-view"),
    path('units-detail-view/<pk>/', views.UnitDetailView.as_view(), name="units-detail-view"),
    path('units-update-view/<pk>/', views.UnitUpdateView.as_view(), name="units-update-view"),
    path('units-delete-view/<pk>/', views.UnitDeleteView.as_view(),
         name="units-delete-view"),
    path('units-list-view/', views.UnitListView.as_view(), name="units-list-view"),
    path('units/index/', views.index, name="units-index"),
    path('units/', views.units, name="units"),
    path('category-create-view/', views.CategoryCreateView.as_view(), name="category-create-view"),
    path('category-detail-view/<pk>/', views.CategoryDetailView.as_view(), name="category-detail-view"),
    path('category-update-view/<pk>/', views.CategoryUpdateView.as_view(), name="category-update-view"),
    path('category-delete-view/<pk>/', views.CategoryDeleteView.as_view(),
         name="category-delete-view"),
    path('category-list-view/', views.CategoryListView.as_view(), name="category-list-view"),
    path('category/index/', views.index, name="index"),
    path('category/', views.category, name="category"),
]

warehouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="homepage"),
    path('admin/', admin.site.urls),
    path('items/', include('items.urls')),
    path('locations/', include('locations.urls')),
    path('orders/', include('orders.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/models.py
from django.db import models
from django.urls import reverse

from items.utils import image_resize
from django.core.validators import MinValueValidator
from locations.models import Location


class Category(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return f" {self.name}"

    class Meta:
        verbose_name_plural = "Categories"


class Unit(models.Model):
    name = models.CharField(max_length=10)
    description = models.CharField(max_length=128, blank=True)
    integer = models.BooleanField(null=False, default=False)
    iso = models.CharField(max_length=16, blank=True, null=True)

    def __str__(self):
        return f" {self.name}"


class Item(models.Model):

    name = models.CharField(max_length=64)
    description = models.CharField(max_length=128, blank=True)
    registration_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name="item_cat", null=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name="item_unit", blank=False, null=False)
    quantity = models.PositiveSmallIntegerField(default=0)
    location = models.ForeignKey(Location, on_delete=models.DO_NOTHING, related_name="items_locations", blank=True, null=True)
    bin = models.CharField(max_length=64, blank=True, null=True)
    producer = models.ForeignKey("Company", on_delete=models.DO_NOTHING, related_name="items_prod", blank=True, null=True)
    producer_no = models.CharField(max_length=50, unique=True, blank=True, null=True)
    supplier = models.ForeignKey("Company", on_delete=models.DO_NOTHING, related_name="items_supp", blank=True, null=True)
    supplier_no = models.CharField(max_length=50, blank=True)
    minimum_quantity = models.PositiveSmallIntegerField(default=1)
    minimum_order = models.PositiveSmallIntegerField(default=0)
    image = models.ImageField(upload_to="items/", blank=True, null=True)

    def __str__(self):
        return f"{self.producer_no}"

    def get_absolute_url(self):
        return reverse("items_app:items-detail-view", kwargs={
            'pk': self.pk
        })

    def get_add_to_cart_url(self):
        return reverse("orders_app:add-to-cart", kwargs={
            'pk': self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("orders_app:remove-from-cart", kwargs={
            'pk': self.pk
        })

    def save(self, *args, **kwargs):
        if self.image:
            image_resize(self.image, 1000, 800)
        super().save(*args, **kwargs)


''' Operations on items for warehouse workers and managers.'''


def input_to_stock(self, amount: float):
    if amount > 0:
        self.quantity += amount


def withdraw(self, amount: float):
    if 0 < amount <= self.quantity:
        self.quantity -= amount


def total_scrap(self):
    self.quantity = 0


def scrap(self, amount: float):
    if 0 < amount <= self.quantity:
        self.quantity -= amount


def return_to_stock(self, amount: float):
    if amount > 0:
        self.quantity += amount


class Company(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField(max_length=64, blank=True)
    phone_no = models.CharField(max_length=30, blank=True)
    contact_person = models.CharField(max_length=64, blank=True)
    website = models.CharField(max_length=128, blank=True)
    minimum_order_value = models.PositiveSmallIntegerField(default=0)

    class Meta:
        verbose_name_plural = "Companies"

    def __str__(self):
        return f" {self.name}"

items/forms.py
import string

from django import forms
import django_filters

from items.models import Item, Company, Category, Unit
from locations.models import Location


class ItemModelForm(forms.ModelForm):
    category = forms.ModelChoiceField(Category.objects.all().order_by("name"))
    unit = forms.ModelChoiceField(Unit.objects.all().order_by("name"))
    location = forms.ModelChoiceField(Location.objects.all().order_by("location"))
    producer = forms.ModelChoiceField(Company.objects.all().order_by("name"))
    supplier = forms.ModelChoiceField(Company.objects.all().order_by("name"))

    class Meta:
        model = Item
        exclude = ["quantity"]


class CompanyModelForm(forms.ModelForm):
    class Meta:
        model = Company
        exclude = []

    def clean_name(self):
        return string.capwords(self.cleaned_data["name"])

    def clean_contact_person(self):
        return string.capwords(self.cleaned_data["contact_person"])

    def clean_email(self):
        return self.cleaned_data["email"].lower()


class ItemFilter(django_filters.FilterSet):
    class Meta:
        model = Item
        exclude = (
            "registration_date",
            "image",
        )

items/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView, DeleteView, UpdateView, DetailView, CreateView

from .forms import CompanyModelForm, ItemModelForm
from .models import Company, Item, Unit, Category
from .filters import ItemFilter


def items(request):
    items_list = Item.objects.all().order_by("name")
    return render(
        request,
        template_name='items/items.html',
        context={'items': items_list},
    )


class ItemCreateView(LoginRequiredMixin, FormView):
    template_name = "form.html"
    form_class = ItemModelForm
    success_url = reverse_lazy("items_app:items-list-view")

    def form_valid(self, form):
        result = super().form_valid(form)
        form.save()
        return result


class CompanyUpdateView(UpdateView):
    model = Company
    fields = "__all__"
    template_name = "form.html"
    success_url = reverse_lazy("items_app:companies")


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    fields = (
        "name",
        "description",
        "category",
        "unit",
        "location",
        "bin",
        "producer",
        "producer_no",
        "supplier",
        "supplier_no",
        "minimum_quantity",
        "minimum_order",
        "image",
    )
    template_name = "form.html"
    success_url = reverse_lazy("items_app:items-list-view")


class CompanyDeleteView(DeleteView):
    model = Company
    template_name = "items/delete.html"
    success_url = reverse_lazy("items_app:companies")


class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    template_name = "items/delete.html"
    success_url = reverse_lazy("items_app:items-list-view")


class CompanyTemplateView(TemplateView):
    template_name = "items/companies.html"
    extra_context = {"object_list": Company.objects.all()}


class CompanyDetailView(DetailView):
    model = Company
    template_name = "items/my_company.html"


class ItemDetailView(DetailView):
    model = Item
    template_name = "items/my_item.html"


class CompanyListView(ListView):
    template_name = "items/companies.html"
    model = Company
    paginate_by = 3

    # def change_pagination(self, number):
    #     if isinstance(number, int):
    #         self.paginate_by = number


class ItemListView(ListView):
    template_name = "items/items.html"
    model = Item

    def get_ordering(self):
        ordering = self.request.GET.get('ordering', 'name')
        return ordering


class CompanyModelFormView(FormView):
    template_name = "form.html"
    form_class = CompanyModelForm
    success_url = reverse_lazy('items_app:companies')

    def form_valid(self, form):
        result = super().form_valid(form)
        form.save()
        return result


def index(request):
    return render(
        request,
        template_name="items/index.html"
    )


def units(request):
    return render(
        request,
        template_name="units/units.html",
        context={"units": Unit.objects.all()}
    )


class UnitCreateView(LoginRequiredMixin, CreateView):
    model = Unit
    template_name = "form.html"
    fields = "__all__"
    success_url = reverse_lazy("items_app:units")


class UnitDeleteView(LoginRequiredMixin, DeleteView):
    model = Unit
    template_name = "units/delete_units.html"
    success_url = reverse_lazy("items_app:units-list-view")


class UnitDetailView(DetailView):
    model = Unit
    template_name = "units/my_units.html"


class UnitListView(ListView):
    model = Unit
    template_name = "units/list_view_units.html"


class UnitUpdateView(LoginRequiredMixin, UpdateView):
    model = Unit
    fields = "__all__"
    template_name = "form.html"
    success_url = reverse_lazy("items_app:units")


def category(request):
    return render(
        request,
        template_name="category/category.html",
        context={"category": Category.objects.all()}
    )


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    template_name = "form.html"
    fields = "__all__"
    success_url = reverse_lazy("items_app:category-list-view")


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    template_name = "category/delete_category.html"
    success_url = reverse_lazy("items_app:category-list-view")


class CategoryDetailView(DetailView):
    model = Category
    template_name = "category/my_category.html"


class CategoryListView(ListView):
    model = Category
    template_name = "category/list_view_category.html"


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    fields = ("name", "description")
    template_name = "form.html"
    success_url = reverse_lazy("items_app:category-list-view")


class SearchResultsView(ListView):
    model = Item
    template_name = "items/items_search.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Item.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query) |
            Q(producer_no__icontains=query) | Q(supplier_no__icontains=query) |
            Q(producer__name__icontains=query) | Q(supplier__name__icontains=query) |
            Q(category__name__icontains=query) | Q(unit__name__icontains=query) |
            Q(location__location__icontains=query) | Q(bin__icontains=query)
        ).order_by('name')
        return object_list


def above_minimum_stock(request):
    items_list = Item.objects.order_by('-quantity').exclude(quantity__lte=0)
    page = request.GET.get('page', 1)

    paginator = Paginator(items_list, 10)
    try:
        items_list = paginator.page(page)
    except PageNotAnInteger:
        items_list = paginator.page(1)
    except EmptyPage:
        items_list = paginator.page(paginator.num_pages)
    return render(
        request,
        template_name='items/items_above_min.html',
        context={'items': items_list},
    )


def search(request):
    items_list = Item.objects.all().order_by('name')
    items_filter = ItemFilter(request.GET, queryset=items_list)
    return render(request, 'items/filter_list.html', {'filter': items_filter})

templates/items/companies.html
{% extends "base.html" %}
{% block content %}
    <p><a href="{% url 'items_app:company-model-form-view' %}">ADD Company</a></p>
<h2>COMPANIES</h2>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="5%">ID</th>
            <th scope="col" width="15%">Name</th>
            <th scope="col" width="20%">Contact</th>
            <th scope="col" width="20%">Min Order Value</th>
        </tr>
        </thead>
        <tbody>
        {% for c in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'items_app:company-detail-view' pk=c.pk %}">{{ c.name }}</a></td>
                <td>{{ c.contact_person }} </td>
                <td>{{ c.minimum_order_value }} PLN</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <header>
{% if page_obj.has_other_pages %}
  <ul class="pagination">
      {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}"> &laquo; </a></li>
    {% else %}
      <li class="disabled"><span> &laquo; </span></li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <a class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
      {% else %}
          <a class="paginator_iter" href="?page={{ i }}"> {{   i  }} </a>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}"> &raquo; </a></li>
    {% else %}
      <li class="disabled"><span> &raquo </span></li>
    {% endif %}
  </ul>
{% endif %}
    </header>

    <a href="{% url 'items_app:items-index' %}">RETURN TO INDEX PAGE</a>
{% endblock %}

templates/items/filter_list.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% block content %}
    {% if request.user.is_staff %}
        <p><a href="{% url 'items_app:items-create-view' %}">ADD ITEM</a></p>
    {% endif %}
  <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Filter Items</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.name.label_tag }}
          {% render_field filter.form.name class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.description.label_tag }}
          {% render_field filter.form.description class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.category.label_tag }}
          {% render_field filter.form.category class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.producer.label_tag }}
          {% render_field filter.form.producer class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.producer_no.label_tag }}
          {% render_field filter.form.producer_no class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.supplier.label_tag }}
          {% render_field filter.form.supplier class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.supplier_no.label_tag }}
          {% render_field filter.form.supplier_no class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.location.label_tag }}
          {% render_field filter.form.location class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.bin.label_tag }}
          {% render_field filter.form.bin class="form-control" %}
        </div>
        </div>
      </div>
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
    </div>
  </form>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Category</th>
        <th>Unit</th>
        <th>Quantity</th>
        <th>Location</th>
        <th>Bin</th>
        <th>Producer</th>
        <th>Producer no</th>
        <th>Supplier</th>
        <th>Supplier no</th>
      </tr>
    </thead>
    <tbody>
      {% for item in filter.qs %}
        <tr>
          <td><a href="{% url 'items_app:items-detail-view' pk=item.pk %}">{{ item.name }}</a></td>
          <td>{{ item.description }}</td>
          <td>{% if item.category %}{{ item.category }}{% endif %}</td>
          <td>{% if item.unit %}{{ item.unit }}{% endif %}</td>
          <td>{{ item.quantity }}</td>
          <td>{% if item.location %}{{ item.location }}{% endif %}</td>
          <td>{% if item.bin %}{{ item.bin }}{% endif %}</td>
          <td>{% if item.producer %}{{ item.producer }}{% endif %}</td>
          <td>{{ item.producer_no }}</td>
          <td>{% if item.supplier %}{{ item.supplier }}{% endif %}</td>
          <td>{{ item.supplier_no }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/items/index.html
{% extends "base.html" %}
{% block content %}
    <p><a href="{% url 'items_app:search-form' %}">ITEM</a></p>
    <p><a href={% url 'items_app:companies' %}>COMPANIES</a></p>
    <p><a href="{% url 'items_app:units' %}">UNITS</a></p>
    <p><a href="{% url 'items_app:category' %}">CATEGORY</a></p>
    <p><a href="{% url 'items_app:items-above-minimum-stock' %}">ITEMS IN STOCK</a></p>
        <a href="{% url 'homepage' %}">
        <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Return
        </button>
    </a>
{% endblock %}

templates/items/items.html
{% extends "base.html" %}
{% block content %}
<h1>ITEMS:</h1>
    <form action="{% url 'items_app:search-result' %}" method="get">
    <input name="q" type="text" placeholder="Search...">
    </form>
    <a href="{% url 'items_app:search-form' %}">FILTER</a>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="5%">No</th>
            <th scope="col" width="15%">Name</th>
            <th scope="col" width="53%">Description</th>
            <th scope="col" width="15%" style="text-align: center; vertical-align: middle;">Producer</th>
            <th scope="col" width="5%" style="text-align: center; vertical-align: middle;">Unit</th>
            <th scope="col" width="7%" style="text-align: center; vertical-align: middle;">Quantity</th>
            <th scope="col" width="7%" style="text-align: center; vertical-align: middle;">Location</th>
            <th scope="col" width="7%" style="text-align: center; vertical-align: middle;">Bin</th>
        </tr>
        </thead>
        <tbody>
        {% for i in object_list %}
            <tr>
                <th scope="row" style="vertical-align: middle;">{{ forloop.counter }}</th>
                <td style="vertical-align: middle;">
                    <a href="{% url 'items_app:items-detail-view' pk=i.pk %}">{{ i.name }}</a></td>
                <td>{{ i.description }} </td>
                <td style="text-align: center; vertical-align: middle;">{% if i.producer %}{{ i.producer }}{% endif %}</td>
                <td style="text-align: center; vertical-align: middle;">{% if i.unit %}{{ i.unit }}{% endif %}</td>
                <td style="text-align: center; vertical-align: middle;">{{ i.quantity }} </td>
                <td style="text-align: center; vertical-align: middle;">{% if i.location %}{{ i.location }}{% endif %}</td>
                <td style="text-align: center; vertical-align: middle;">{% if i.bin %}{{ i.bin }}{% endif %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if request.user.is_staff %}
        <p><a href="{% url 'items_app:items-create-view' %}">ADD ITEM</a></p>
    {% endif %}
    <a href="{% url 'items_app:items-index' %}">RETURN TO INDEX PAGE</a>
{% endblock %}

templates/items/items_search.html
{% extends "base.html" %}
{% block content %}
<h1>ITEMS:</h1>
<table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="5%">No</th>
            <th scope="col" width="15%">Name</th>
            <th scope="col" width="53%">Description</th>
            <th scope="col" width="15%" style="text-align: center; vertical-align: middle;">Producer</th>
            <th scope="col" width="5%" style="text-align: center; vertical-align: middle;">Unit</th>
            <th scope="col" width="7%" style="text-align: center; vertical-align: middle;">Quantity</th>
            <th scope="col" width="7%" style="text-align: center; vertical-align: middle;">Location</th>
            <th scope="col" width="7%" style="text-align: center; vertical-align: middle;">Bin</th>
        </tr>
        </thead>
        <tbody>
        {% for o in object_list %}
            <tr>
                <th scope="row" style="vertical-align: middle;">{{ forloop.counter }}</th>
                <td style="vertical-align: middle;">
                    <a href="{% url 'items_app:items-detail-view' pk=o.pk %}">{{ o.name }}</a></td>
                <td>{{ o.description }} </td>
                <td style="text-align: center; vertical-align: middle;">{% if o.producer %}{{ o.producer }}{% endif %}</td>
                <td style="text-align: center; vertical-align: middle;">{% if o.unit %}{{ o.unit }}{% endif %} </td>
                <td style="text-align: center; vertical-align: middle;">{{ o.quantity }} </td>
                <td style="text-align: center; vertical-align: middle;">{% if o.location %}{{ o.location }}{% endif %}</td>
                <td style="text-align: center; vertical-align: middle;">{% if o.location %}{{ o.bin }}{% endif %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if request.user.is_staff %}
        <p><a href="{% url 'items_app:items-create-view' %}">ADD ITEM</a></p>
    {% endif %}
    <a href="{% url 'items_app:index' %}">RETURN TO INDEX PAGE</a>
{% endblock %}

templates/items/list_view.html
{% extends "base.html" %}
{% block content %}
    {% for o in object_list %}
        <li> {{ o }} </li>
    {% endfor %}
    <a href="{% url 'items_app:index' %}">RETURN TO INDEX PAGE</a>
{% endblock %}

templates/items/my_company.html
{% extends "base.html" %}
{% block content %}
    <p>Company ID: {{ company.id }}</p>
    <p>Company Name: {{ company.name }}</p>
    <p><a href="{% url 'items_app:company-update-view' pk=company.pk %}">UPDATE</a></p>
    <p><a href="{% url 'items_app:company-delete-view' pk=company.pk %}">DELETE</a></p>
    <a href="{% url 'items_app:items-index' %}">RETURN TO INDEX PAGE</a>
{% endblock %}

templates/items/my_item.html
{% extends "base.html" %}
{% block content %}
<h3>ITEMS DETAILS</h3>
            <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to order
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="20%" style="vertical-align: middle;">Name</th>
            <th scope="col" width="50%" style="vertical-align: middle;">Description</th>
            <th scope="col" width="9%" style="text-align: center; vertical-align: middle;">Category</th>
            <th scope="col" width="6%" style="text-align: center; vertical-align: middle;">Unit</th>
            <th scope="col" width="5%" style="text-align: center; vertical-align: middle;">Qty</th>
            <th scope="col" width="5%" style="text-align: center; vertical-align: middle;">Location</th>
            <th scope="col" width="5%" style="text-align: center; vertical-align: middle;">Bin</th>
        </tr>
        <tr>
            <td style="vertical-align: middle;">{{ item.name }}</td>
            <td style="vertical-align: middle;">{{ item.description }}</td>
            <td style="text-align: center; vertical-align: middle;">{% if item.category %}{{ item.category }}{% endif %}</td>
            <td style="text-align: center; vertical-align: middle;">{% if item.unit %}{{ item.unit }}{% endif %}</td>
            <td style="text-align: center; vertical-align: middle;">{{ item.quantity }}</td>
            <td style="text-align: center; vertical-align: middle;">{% if item.location %}{{ item.location }}{% endif %}</td>
            <td style="text-align: center; vertical-align: middle;">{% if item.bin %}{{ item.bin }}{% endif %}</td>
        </tr>
        </thead>
    </table>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="20%" style="vertical-align: middle;">Producer</th>
            <th scope="col" width="15%" style="vertical-align: middle;">Producer no</th>
            <th scope="col" width="20%" style="text-align: center; vertical-align: middle;">Supplier</th>
            <th scope="col" width="15%" style="text-align: center; vertical-align: middle;">Supplier no</th>
            <th scope="col" width="15%" style="text-align: center; vertical-align: middle;">Min stock</th>
            <th scope="col" width="15%" style="text-align: center; vertical-align: middle;">Min order qty</th>
        </tr>
        <tr>
            <td>{% if item.producer %}{{ item.producer }}{% endif %}</td>
            <td>{{ item.producer_no }}</td>
            <td style="text-align: center; vertical-align: middle;">{% if item.supplier %}{{ item.supplier }}{% endif %}</td>
            <td style="text-align: center; vertical-align: middle;">{{ item.supplier_no }}</td>
            <td style="text-align: center; vertical-align: middle;">{{ item.minimum_quantity }}</td>
            <td style="text-align: center; vertical-align: middle;">{{ item.minimum_order }}</td>
        </tr>
        </thead>
    </table>
    <div>
        {% if item.image.url is not null %}
        <img class="picture" src="{{ item.image.url }}" alt="{{ item.name }}">
        {% endif %}
    </div>
    {% if request.user.is_staff %}
        <p><a href="{% url 'items_app:items-update-view' pk=item.pk %}">UPDATE</a></p>
        <p><a href="{% url 'items_app:items-delete-view' pk=item.pk %}">DELETE</a></p>
    {% endif %}
    <a href="{% url 'items_app:search-form' %}">GO BACK</a>
{% endblock %}